/**
 * Landing page HTML for wrapped-claude-codes.adewale-883.workers.dev
 * Stark, Tufte-inspired design matching the Print view
 */

export function renderLandingPage(): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Claude Code Wrapped</title>
  <meta name="description" content="Your year in code with Claude. Generate a shareable summary of your development journey.">
  <meta property="og:title" content="Claude Code Wrapped">
  <meta property="og:description" content="Your year in code with Claude. See your development journey.">
  <meta property="og:type" content="website">
  <meta name="twitter:card" content="summary_large_image">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Source+Serif+4:ital,opsz,wght@0,8..60,400;0,8..60,600;0,8..60,700;1,8..60,400&display=swap" rel="stylesheet">
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    :root {
      --text: #1a1a1a;
      --text-light: #666;
      --border: #ddd;
      --bg: #ffffff;
    }

    body {
      font-family: 'Source Serif 4', Georgia, serif;
      background: var(--bg);
      color: var(--text);
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      padding: 2rem;
      font-size: 13pt;
      line-height: 1.55;
      letter-spacing: 0.01em;
    }

    .container {
      max-width: 640px;
      width: 100%;
    }

    .header {
      border-bottom: 2px solid var(--text);
      padding-bottom: 1rem;
      margin-bottom: 2rem;
    }

    h1 {
      font-size: 2.5rem;
      font-weight: 700;
      letter-spacing: -0.025em;
      margin-bottom: 0.5rem;
    }

    .subtitle {
      color: var(--text);
      font-style: italic;
      font-size: 1.15rem;
    }

    .section {
      margin-bottom: 2rem;
    }

    .section-title {
      font-size: 0.85rem;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.12em;
      color: var(--text-light);
      margin-bottom: 0.75rem;
      border-bottom: 1px solid var(--border);
      padding-bottom: 0.25rem;
    }

    .command-box {
      border: 1px solid var(--border);
      padding: 1rem;
      font-family: 'SF Mono', Monaco, 'Courier New', monospace;
      font-size: 0.95rem;
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 1rem;
    }

    .command-box code {
      flex: 1;
    }

    .copy-btn {
      background: none;
      border: 1px solid var(--border);
      color: var(--text-light);
      cursor: pointer;
      padding: 0.35rem 0.5rem;
      font-size: 0.7rem;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      transition: all 0.2s;
    }

    .copy-btn:hover {
      color: var(--text);
      border-color: var(--text);
    }

    .feature-list {
      list-style: none;
    }

    .feature-list li {
      padding: 0.4rem 0;
      border-bottom: 1px solid var(--border);
      display: flex;
      align-items: baseline;
      gap: 0.5rem;
    }

    .feature-list li:last-child {
      border-bottom: none;
    }

    .feature-bullet {
      color: var(--text-light);
      font-size: 0.8rem;
    }

    .privacy-note {
      font-size: 0.9rem;
      padding: 1rem;
      border: 1px solid var(--border);
      background: #fafafa;
    }

    .privacy-note strong {
      font-weight: 600;
    }

    footer {
      margin-top: 2rem;
      padding-top: 1rem;
      border-top: 1px solid var(--border);
      color: var(--text-light);
      font-size: 0.75rem;
      letter-spacing: 0.03em;
      text-align: center;
    }

    a {
      color: var(--text);
      text-decoration: underline;
      text-underline-offset: 2px;
    }

    a:hover {
      color: var(--text-light);
    }

    footer a {
      text-decoration: none;
    }

    footer a:hover {
      text-decoration: underline;
    }

    @media (max-width: 640px) {
      body {
        padding: 1.5rem;
        font-size: 11pt;
      }
      h1 {
        font-size: 1.75rem;
      }
      .subtitle {
        font-size: 1rem;
      }
      .command-box {
        flex-direction: column;
        gap: 0.75rem;
        text-align: center;
      }
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>Claude Code Wrapped</h1>
      <p class="subtitle">Your year in code with Claude</p>
    </div>

    <div class="section">
      <div class="section-title">About</div>
      <p>Generated by <a href="https://github.com/adewale/claude-history-explorer">Claude History Explorer</a>, a Python CLI tool to explore, search and visualise your Claude Code conversation history.</p>
    </div>

    <div class="section">
      <div class="section-title">Generate</div>
      <div class="command-box">
        <code>claude-history wrapped</code>
        <button class="copy-btn" onclick="copyCommand()">Copy</button>
      </div>
    </div>

    <div class="section">
      <div class="section-title">What You'll See</div>
      <ul class="feature-list">
        <li><span class="feature-bullet">-</span> Message count, hours coded, projects</li>
        <li><span class="feature-bullet">-</span> Weekly activity heatmap</li>
        <li><span class="feature-bullet">-</span> Monthly sparkline</li>
        <li><span class="feature-bullet">-</span> Coding style traits</li>
        <li><span class="feature-bullet">-</span> Shareable URL</li>
      </ul>
    </div>

    <div class="section">
      <div class="section-title">Example</div>
      <p><a href="/wrapped?d=3gAXoXYDoXnNB-mhbqlEZW1vIFVzZXKhbc0LH6FozJyhcAihc3yhZFmibHPLQBDMzMzMzM2iaG3cAKgCAAECAQAEBgYNDQsFBw0PDw4ICAcCAgMBAAEAAAAGBgQMDQwGBQ4ODg4JCQgCBAQAAAACAgIFBgYNCwwHBQ0NDw0JBwkEBAMAAQAAAAEGBgQNCw0FBw8ODw4HCQkDBAICAQEBAAAGBQQNCwsFBw0NDw8ICAgCBAIAAAACAgEBAgIDBAUEAgUEBAUFBgUCAwQAAgEBAQABAgEFAwQDAwYGBgUHBwcDAwKibWGcVcyOzMbNAQvNATjNAR3NAVXNASrNAQDM4My9zPqibWicCAsOEhUTGBQRDwwRom1znAYJDA4QDxIQDQsJDKJzZIqiYWREonNwKqJmY0uiY2MjondyOqJicy2iY3M-om12JqJ0ZEeicmk0omFymggMEhgWEAoGAwGibWyWojUwozEyMKMyODCjNDUwozYyMKM4NTCidHOGomFkRKJzcCqiZmNLomJzLaJjcz6icmk0onRwlpa3Y2xhdWRlLWhpc3RvcnktZXhwbG9yZXLNA3w0Ii1Ilq93cmFwcGVkLXdlYnNpdGXNAnomHCBBlq1wZXJzb25hbC1zaXRlzQGcGBIWMJaqYXBpLWNsaWVudM0BHxAMDyOWqGRvdGZpbGVzzJwICAoWlqdzY3JpcHRzYgUFBg-icGOVkwABHJMAAgyTAQIIkwADBpMCBASidGWVlC0ALwCUAQEM_5RZBM0D6P-UeAP_AZTMyAA0AaJzZpOey0AMAAAAAAAALQEOAgBIQU5SLQxEN57LQADMzMzMzM0cAAoAATpIQEYmCDQwnstAEMzMzMzMzT4BEAMAVU5YXDQPSz6ic2uUDA4FBqJ0a4aldG90YWzOAIGzIKVpbnB1dM4AT1iApm91dHB1dM4AMlqgqmNhY2hlX3JlYWTOABJPgKxjYWNoZV9jcmVhdGXOAAbd0KZtb2RlbHOCpnNvbm5ldM4AZ8KApWhhaWt1zgAZ8KA">View an example with sample data</a></p>
    </div>

    <div class="section">
      <div class="privacy-note">
        <strong>Privacy:</strong> All data is encoded in the URL itself.
        We (the Wrapped web site) never see, store, or process your code or conversations.
      </div>
    </div>

    <footer>
      Built on <a href="https://developers.cloudflare.com/" target="_blank" rel="noopener">the Cloudflare Developer Platform</a>
    </footer>
  </div>

  <script>
    function copyCommand() {
      navigator.clipboard.writeText('claude-history wrapped');
      const btn = document.querySelector('.copy-btn');
      const original = btn.textContent;
      btn.textContent = 'Copied';
      btn.style.borderColor = '#1a1a1a';
      btn.style.color = '#1a1a1a';
      setTimeout(() => {
        btn.textContent = original;
        btn.style.borderColor = '';
        btn.style.color = '';
      }, 2000);
    }
  </script>
</body>
</html>`;
}
